services:
  - type: web
    name: chox-kitchen
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
